---

- name: "list files from {{ vitamui_defaults.folder.root_path | default('/vitamui') }}/log/{{ component_name }}"
  find:
    paths: "{{ vitamui_defaults.folder.root_path | default('/vitamui') }}/log/{{ component_name }}"
    age: "-{{ log_files_age }}d"
    recurse: no # no subdir
    file_type: file
    excludes: "java_pid*,{{ excludes | default('') }}"
  register: path_files

# Run the rest only if there is files to get
- name: handle files for log
  include_tasks: handle_files.yml
  vars:
    component: "{{ component_name }}"
    sufix: log
