---

# Run the rest only if there is files to get
- block:

  - name: create list of files
    set_fact: fichier="{{ item.path }}"
    with_items: "{{ path_files.files }}"
    register: filespath

  - name: Create a temp zip archive from {{ component_name }}
    archive:
      path: "{{ filespath.results| map(attribute='ansible_facts.fichier') | list }}"
      dest: "{{ vitamui_defaults.folder.root_path | default('/vitamui') }}/tmp/{{ component_name }}/{{ component_name }}_{{ suffix }}.zip"
      format: zip

  - name: fetch zip file from {{ component_name }} with rsync method
    synchronize:
      mode: pull
      src: "{{ vitamui_defaults.folder.root_path | default('/vitamui') }}/tmp/{{ component_name }}/{{ component_name }}_{{ suffix }}.zip"
      dest: "{{ inventory_dir }}/troubleshoot/{{ inventory_hostname }}/{{ component_name }}/"
    when: sync_type | default('fetch') | lower == 'rsync'

  - name: fetch zip file from {{ component_name }} with fetch method
    fetch:
      src: "{{ vitamui_defaults.folder.root_path | default('/vitamui') }}/tmp/{{ component_name }}/{{ component_name }}_{{ suffix }}.zip"
      dest: "{{ inventory_dir }}/troubleshoot/{{ inventory_hostname }}/{{ component_name }}/{{ component_name }}_{{ suffix }}.zip"
      flat: yes
    when: sync_type | default('fetch') | lower == 'fetch'

  - name: remove temp zip file on host
    file:
      path: "{{ vitamui_defaults.folder.root_path | default('/vitamui') }}/tmp/{{ component_name }}/{{ component_name }}_{{ suffix }}.zip"
      state: absent

  when: path_files is defined and path_files.matched > 0