---

- name: init troubleshoot directories
  file:
    path: "{{ inventory_dir }}/troubleshoot/{{ inventory_hostname }}/"
    state: directory
    mode: 0777
  delegate_to: localhost

# If sync_type == 'rsync'
- block:

  - name: ensure rsync package is installed for synchronize module
    package:
      name: rsync
      state: present
    register: result
    retries: "{{ packages_install_retries_number }}"
    until: result is succeeded
    delay: "{{ packages_install_retries_delay }}"

  - name: ensure rsync is installed locally for synchronize module
    package:
      name: rsync
      state: present
    register: result
    retries: "{{ packages_install_retries_number }}"
    until: result is succeeded
    delay: "{{ packages_install_retries_delay }}"
    run_once: true
    delegate_to: localhost

  when: sync_type | default('fetch') | lower == 'rsync'

# Gather hosts information
- name: gather facts
  setup:
  register: faits

- name: get back facts
  copy:
    content: "{{ faits }}"
    dest: "{{ inventory_dir }}/troubleshoot/{{ inventory_hostname }}/facts.json"
    mode: 0775
  delegate_to: localhost

- name: get back /etc/resolv.conf
  fetch:
    src: "/etc/resolv.conf"
    dest: "{{ inventory_dir }}/troubleshoot/{{ inventory_hostname }}/resolv.conf"
    flat: yes

# Tree deployment package
- block:

  - name: Install tree package
    ignore_errors: true
    become: true
    package:
      name: tree
      state: present
    register: result
    retries: "{{ packages_install_retries_number }}"
    until: result is succeeded
    delay: "{{ packages_install_retries_delay }}"
    delegate_to: localhost

  - name: list all files
    ignore_errors: true
    shell: tree -a ../ > {{ inventory_dir }}/troubleshoot/listing_ansible.txt
    delegate_to: localhost

  run_once: true

# Check VitamUI directories
- name: check whether VITAMUI parent dir already exists
  stat:
    path: "{{ vitamui_defaults.folder.root_path }}"
  register: root_dir
      
- name: fail if this VITAMUI parent dir is a symlink
  copy:
    content: "root vitam dir is symlink"
    dest: "{{ inventory_dir }}/troubleshoot/{{ inventory_hostname }}/vitamui_root_dir_symlink.txt"
  delegate_to: localhost
  when: root_dir.stat.islnk is defined and root_dir.stat.islnk == "true"
