---

- name: set mapping service to host
  set_fact:
    services:
      - 'iam-internal'
      - 'iam-external'
      - 'ingest-internal'
      - 'ingest-external'
      - 'referential-internal'
      - 'referential-external'
      - 'security-internal'
      - 'archive-search-internal'
      - 'archive-search-external'
      - 'ui-identity'
      - 'ui-portal'
      - 'ui-search'
      - 'ui-ingest'
      - 'ui-referential'
      - 'ui-archive-search'
      - 'ui-identity-admin'
      - 'cas-server'

- name: troubleshoot - init
  include_tasks: init_troubleshoot.yml
  
- name: troubleshoot - get consul state
  include_tasks: consul_state.yml

- name: troubleshoot - get log for services
  include_tasks: get_app_log.yml
  vars:
    component_name: "{{ item }}"
    suffix: log
  with_items:
    - "{{ services }}"

- name: troubleshoot - get configuration for service
  include_tasks: get_app_conf.yml
  vars:
    component_name: "{{ item }}"
    suffix: conf
  with_items:
    - "{{ services }}"

- name: troubleshoot - get crt files
  include_tasks: get_crt_files.yml
  when: get_crt | default(false) | bool == true

- name: troubleshoot - end
  include_tasks: end_troubleshoot.yml
