---
# Example: ansible-playbook -i environments/<hosts vitamui file> troubleshoot.yml -e 'confirmation=YES log_files_age=2'
# Optional parameters: -e 'sync_type=rsync get_crt=yes excludes=gc*,access*'

# Confirm launching this playbook and check log_files_age parameter
- hosts: localhost
  any_errors_fatal: yes
  gather_facts: no
  vars_prompt:

    - name: confirmation
      prompt: "This playbook will collect logs and other useful information to help debugging your VitamUI instance.\n\nAre you sure you want to run this playbook ?\nAnswer with 'YES'"
      default: "NO"
      private: no

    - name: log_files_age
      prompt: "Type the maximum age of the files you want to retrieve (in days)"
      default: 2
      private: no

  tasks:

    - name: Check Confirmation
      fail: msg="Playbook run confirmation failed"
      when: confirmation | default(false) | bool == false

    - name: Age check
      fail:
        msg: "log_files_age is not valid: {{ log_files_age }} <= 0"
      when: log_files_age | int <= 0

    - name: Register var
      set_fact:
        log_files_age: "{{ log_files_age }}"

  run_once: true

- hosts: hosts_vitamui
  gather_facts: no
  become: true
  roles:
    - troubleshoot
