---

# Mongodb migration from 4.2 to 4.4
######################################

# Confirm launching this playbook
- hosts: localhost
  any_errors_fatal: yes
  gather_facts: no
  vars_prompt:
    name: "confirmation"
    prompt: "Are you sure you want to run this playbook ?\nAnswer with 'YES'"
    default: "NO"
    private: no
  tasks:
    - name: Check Confirmation
      fail: msg="Playbook run confirmation failed"
      when: confirmation|upper != "YES"

####################################
# Début de la migration mongod #
####################################

#########################
########## 4.4 ##########
#########################

# Arrêt du balancer

# - hosts: hosts_mongos_data
#   roles:
#     - mongodb_balancer
#   vars:
#     mongo_group: hosts_mongos_data
#     state: stopped

# mongod 4.4

- hosts: hosts_vitamui_mongod
  roles:
    - mongodb_migration_v44
  vars:
    mongo_group: hosts_mongod_data
    mongo_type: mongod
    mongo_port: "{{ mongodb.mongod_port }}"
    action: mongodb_set_members_groups

- hosts: hosts_vitamui_mongod
  roles:
    - mongodb_migration_v44
  vars:
    mongo_group: hosts_mongod_data
    mongo_type: mongod
    mongo_port: "{{ mongodb.mongod_port }}"
    mongo_version: 4.4.0
    mongo_primary: false
    action: mongodb_upgrade_package
  serial: 1

- hosts: hosts_vitamui_mongod
  roles:
    - mongodb_migration_v44
  vars:
    mongo_group: hosts_mongod_data
    mongo_type: mongod
    mongo_port: "{{ mongodb.mongod_port }}"
    mongo_version: 4.4.0
    mongo_primary: true
    action: mongodb_upgrade_package
  serial: 1

# Fin de la migration: redémarrage du balancer

# - hosts: hosts_mongos_data
#   roles:
#     - mongodb_balancer
#   vars:
#     mongo_group: hosts_mongos_data
#     state: started

# set_featurecompatibility

# - hosts: hosts_mongos_data
#   roles:
#     - mongodb_set_feature_compatibility
#   vars:
#     mongo_group: hosts_mongos_data
#     mongo_version: "4.4"

##################################
# Fin de la migration mongod     #
##################################