##########################################
# Back runners configuration
##########################################
server:
  port: 9800

server-identity:
  identityName: vitamui-dev
  identityRole: integration-tests
  identityServerId: 1

certs-folder: certs/local/
generic-cert: ${certs-folder}/generic-it.jks
jks-password: FOlyWYMRTIsTqdZiAFKcj9vHbDEw5nn88ZDBNEqUaIPDsg9d

# Iam client configuration
iam-client:
  host: 172.18.96.50
  port: 8101
  ssl:
    keystore:
      path: ${certs-folder}/keystore_ui-identity.jks
      password: vcogGlobOTd6hdsBzzT9ya0DYOBO6kHCYgVgg8ZaoeY0iQbe
    truststore:
      path: ${certs-folder}/truststore_server.jks
      password: wcS9Xye1GXSYLvtlDAVAZ3GRZbm1uFu3IFsLKLIx0QAPLaK5


# Mongo
mongo:
  iam.uri: mongodb://api-iam:iam1234@172.18.96.50:27017/iam?connectTimeoutMS=2000
  security.uri: mongodb://api-security:security1234@172.18.96.50:27017/security?connectTimeoutMS=2000

# Workspace configuration
workspace:
  workspace.path: /tmp/workspace-vitamui
  workspace.tempPath: /tmp/workspace-vitamui.tmp

environnement: dev

user:
  demo:
    email: demo@vitamui.com
    password: password
  admin:
    email: admin@vitamui.com
    password: password

trace:
  enabled: false
  timeOutInInSeconds: 60

flow:
  sleep.duration: 2000
  timeout: 10000

vitamui_platform_informations:
  name: system_customer
  description: System Customer
  company_name: system_company
  default_email_domain: change-it.fr
  email_domains: change-it.fr
  default_password: change-it
  address:
    street: change-it
    zip_code: change-it
    city: change-it
    country: change-it
  proof_tenant: 1
  cas_tenant: -1
  first_customer_tenant: 9
  system_archive_tenant_identifier: 9
  client1_tenant_identifier: 102
  platform_name: VITAM-UI
